name: Publish vcpkg package
on:
  push:
    branches:
      - master
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Vcpkg
      uses: thedoctor0/zip-release@master
      with:
        filename: 'nnoops-long-arith-vcpkg.zip'
        path: vcpkg/
        type: zip
    - name: Create PR
      uses: peter-evans/create-pull-request@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: Update vcpkg archive
        committer: Mr-Leshiy Mr-Leshiy leshiy12345678@gmail.com
        author: Mr-Leshiy Mr-Leshiy leshiy12345678@gmail.com
        title: "Update the archive of the vcpkg"
        draft: false
        branch: update-vcpkg-archive
        delete-branch: true
        request-to-parent: false
