name: Create Archive
on: [push]
jobs: 
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Archive Vcpkg
      uses: thedoctor0/zip-release@master
      with:
        filename: 'nnoops-long-arith-vcpkg.zip'
        path: vcpkg/
        type: zip